version: '3.5'

services:
  suits-auth:
    image: suitsims/suits-auth:1.0.0
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  suits-api:
    image: suitsims/suits-api:0.0.1-SNAPSHOT
    expose:
      - 8080
    ports:
      - 8080:8080
    env_file: .env
    links:
      - suits-auth
      - suits-database

  suits-database:
    image: postgres:11
    expose:
      - 5432
    environment:
      - POSTGRES_USER=suits
      - POSTGRES_PASSWORD=suits
      - POSTGRES_DB=suits

