version: '3.5'

services:
  suits-auth:
    image: jboss/keycloak
    volumes:
      - .tools/realm/suits-ims-realm.json:/tmp/suits-ims-realm.json
    expose:
      - 8080
    ports:
      - 8089:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/suits-ims-realm.json
